#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Ejecutando ESLint..."
npm run lint

if [ $? -ne 0 ]; then
  echo "❌ Error: Hay errores en tu JavaScript."
  exit 1
fi

echo "✔ ESLint OK. Commit permitido."
